---
title: "Time Series"
author: "Cody Frisby"
date: "April 4, 2016"
output: 
  html_document: 
    keep_md: yes
---

```{r, warning=F, message=F}
library(tseries)
# read a time series file
z <- read.ts("~/Documents/MATH3710/timeseries/data/papertowels1.txt")
t <- 1:length(z)
# we may not need the above line when using R.
w <- diff(z, lag = 1)
tw <- 1:length(w)
# we can create a time series object by using ts(x)
# more computations from class example
# sample auto correlation at lag k=3
r3 <- sum((z - mean(z))*(z[-(1:3)]-mean(z)))
var.z <- sum((z-mean(z))^2)
r3/var.z # this doesn't work... see acf below for the correct values
```


```{r, dpi=200, fig.align='center'}
par(mfrow=c(1,2))
plot(as.numeric(z), xlab = "Week", ylab = "z")
plot(as.numeric(w), xlab = "Week", ylab = "w")
```

z and w are of class "ts" (time series).  When you plot an object of this class in R you get  

```{r, dpi=200, fig.align='center'}
par(mfrow=c(1,2))
plot(z, xlab = "Week")
plot(w, xlab = "Week")
```

###PROC ARIMA in SAS, here we run the same analysis in R  
```{r, dpi=200, fig.align='center'}
fit.ts <- arima(z) # fit a univariate time series
fit.ts
a <- acf(z) # autocorrelations plot
matrix(a$acf[-1]) #autocorelations table
#adf.test(z) # don't include yet
```


```{r, dpi=200, fig.align='center'}
par(mfrow=c(2,2))
ts.plot(z)
acf(z)
pacf(z)
```

Trend and correlation analysis for W

```{r, dpi=200, fig.align='center'}
sac <- acf(w, plot = FALSE)
matrix(sac$acf[-1])
par(mfrow=c(2,2))
ts.plot(w)
acf(w)
spac <- pacf(w, plot = FALSE)
matrix(spac$acf)
```


```{r, warning=F, message=F}
library(forecast)
accuracy(fit.ts) #accuracy test of our above time series
```

You may need to install the R package *tseries* by

```{r, eval=F}
install.packages("tseries")
```


#Problem Set  

## Toothpaste example  

```{r}
library(tseries)
# I saved the data in the SAS program to a txt file.
z <- read.ts("~/Documents/MATH3710/datafiles/toothpaste.txt")
w <- diff(z, lag = 1) # first differences
ts <- arima(z) # no fit yet
plot(z) #is this stationary?  NO!
plot(w) # much more "stationary", Yes

# r_2 calculation, using first 10 z_i
z.8 <- z[1:8]; z.10 <- z[1:10]
nume <- sum((z.8 - mean(z.10))*(z.10[3:10] - mean(z.10)))
denom <- sum((z.10 - mean(z.10))^2)
nume/denom

# fit an AR1 model
ar1 <- arima(w, c(1,0,0))
```


## Viscosity Example  

```{r}
# the txt file is in the datafiles directory
z <- read.ts("~/Documents/MATH3710/datafiles/viscosity.txt")
ar0 <- arima(z)
```


## Shampoo Example

```{r}
z <- read.ts("~/Documents/MATH3710/datafiles/time.txt")
e <- cbind(acf(z)$acf[-1], pacf(z)$acf)[1:7,]
colnames(e) <- c("r_k", "r_kk")
e
arima(z) # original model
# first differences model
w <- diff(z, lag = 1)
arima(w)
e <- cbind(acf(w, plot = FALSE)$acf[-1], pacf(w, plot = FALSE)$acf)[1:7,]
colnames(e) <- c("r_k", "r_kk")
e
```






## Example of Time Series using R  

###Air Passengers Example:

```{r, dpi=200, fig.align='center'}
air <- AirPassengers
par(mfrow=c(2,2))
ts.plot(air)
acf(air)
pacf(air)
```

```{r, dpi=200, fig.align='center'}
plot(decompose(air))
```

### ARIMA model
```{r, warning=F, message=F, dpi=200}
air.fit <- arima(air,order=c(0,1,1), seasonal=list(order=c(0,1,1),
                                                   period=12))
tsdiag(air.fit)
library(forecast)
air.forecast <- forecast(air.fit)
plot.forecast(air.forecast)
```
